export const FORMATS = [
    { format: 'AVIF', decoding: 'Only 8-bit' },
    { format: 'BMP', decoding: 'Yes' },
    { format: 'DDS', decoding: 'DXT1, DXT3, DXT5' },
    { format: 'Farbfeld', decoding: 'Yes' },
    { format: 'GIF', decoding: 'Yes' },
    { format: 'HDR', decoding: 'Yes' },
    { format: 'ICO', decoding: 'Yes' },
    { format: 'JPEG', decoding: 'Baseline and progressive' },
    { format: 'JPG', decoding: 'Baseline and progressive' },
    { format: 'OpenEXR', decoding: 'Rgb32F, Rgba32F (no dwa compression)' },
    { format: 'PNG', decoding: 'All supported color types' },
    { format: 'PNM', decoding: 'PBM, PGM, PPM, standard PAM' },
    { format: 'QOI', decoding: 'Yes' },
    { format: 'TGA', decoding: 'Yes' },
    { format: 'TIFF', decoding: 'Baseline(no fax support) + LZW + PackBits' },
    { format: 'WebP', decoding: 'Yes' },
];
